### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by thfght** [thfght/htmlproject#1]
just add hello world

**Comment by pldnz** [comment]
hello, I would like to collaborate, could you assign me to the task

**Comment by Dihfj** [comment]
Ohk just made simple html form 🙂

**Comment by educationalgamer** [comment]
<html>
<head>
<title>anshu</title>
<head>
<body><h1>an</h1>
</body>
</html>

**Comment by thfght** [comment]
Thank you
